maven_build:
  image: maven:3.6.3-jdk-11
  variables:
    _JAVA_OPTIONS: "-Djava.awt.headless=true"
  script: mvn test

sonarqube-check:
  image: maven:3.6.3-jdk-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
    _JAVA_OPTIONS: "-Djava.awt.headless=true"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn clean verify sonar:sonar -Dsonar.id=210363 -Dsonar.login=sqp_a00556d98f0b2164bdb3d02edcacd20e06182f68
  allow_failure: true
